/* UR Fit service worker. Generated by tools/pages.js, do not edit by hand.
 *
 * Scope is /fit/ only, because the file sits at /fit/sw.js. The marketing
 * pages are not controlled or cached by this worker on purpose: they change
 * with every deploy and are cache-busted by tools/build-dist.sh, and a worker
 * that wedged the shop would be a worse outcome than no worker.
 *
 * Network-first for navigations with the cached shell as the offline
 * fallback; stale-while-revalidate for same-origin assets; the API is never
 * cached or intercepted. The engine files (model, wasm) are cached on demand
 * by the asset strategy, never in install.
 */
'use strict';

const SHELL_VERSION = 'v2';
const SHELL_CACHE = 'ur-fit-' + SHELL_VERSION;
const NAV_FALLBACK = '/fit/';
const SHELL_ASSETS = [
  '/fit/',
  '/fit/manifest.webmanifest',
  '/assets/ur.css',
  '/assets/ur-data.js',
  '/assets/ur-common.js',
  '/assets/ur-capture.js',
  '/assets/ur-measure.js',
  '/assets/ur-profile.js',
  '/assets/ur-fit.js'
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(SHELL_CACHE)
      .then(function (cache) { return cache.addAll(SHELL_ASSETS); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil((async function () {
    var keys = await caches.keys();
    await Promise.all(keys.map(function (k) {
      return k === SHELL_CACHE ? null : caches.delete(k);
    }));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', function (event) {
  var request = event.request;
  if (request.method !== 'GET') return;
  var url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // Reservations and the waitlist must always reach the network or fail
  // loudly. Never cached, never synthesized from a cache.
  if (url.pathname.indexOf('/api/') === 0) return;

  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
  } else {
    event.respondWith(staleWhileRevalidate(request));
  }
});

async function networkFirst(request) {
  var cache = await caches.open(SHELL_CACHE);
  try {
    var fresh = await fetch(request);
    if (fresh && fresh.ok) cache.put(request, fresh.clone());
    return fresh;
  } catch (err) {
    // Offline: fall back to the cached shell, ignoring any ?pair= query.
    var hit = await cache.match(request, { ignoreSearch: true });
    if (hit) return hit;
    var shell = await cache.match(NAV_FALLBACK);
    if (shell) return shell;
    throw err;
  }
}

async function staleWhileRevalidate(request) {
  var cache = await caches.open(SHELL_CACHE);
  // The dist build stamps assets with ?v=, so match on the path alone.
  var hit = await cache.match(request, { ignoreSearch: true });
  var refresh = fetch(request).then(function (response) {
    if (response && response.ok) cache.put(request, response.clone());
    return response;
  }).catch(function () { return null; });
  if (hit) return hit;
  var fresh = await refresh;
  if (fresh) return fresh;
  return new Response('offline', { status: 503, statusText: 'Offline' });
}
